//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWithProxyClass.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDiskInfo")]
    public interface IDiskInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/GetTotalSpace", ReplyAction="http://tempuri.org/IDiskInfo/GetTotalSpaceResponse")]
        long GetTotalSpace(string strDiskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/GetTotalSpace", ReplyAction="http://tempuri.org/IDiskInfo/GetTotalSpaceResponse")]
        System.Threading.Tasks.Task<long> GetTotalSpaceAsync(string strDiskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/GetFreeSpace", ReplyAction="http://tempuri.org/IDiskInfo/GetFreeSpaceResponse")]
        long GetFreeSpace(string strDiskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/GetFreeSpace", ReplyAction="http://tempuri.org/IDiskInfo/GetFreeSpaceResponse")]
        System.Threading.Tasks.Task<long> GetFreeSpaceAsync(string strDiskName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiskInfoChannel : ClientWithProxyClass.ServiceReference.IDiskInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiskInfoClient : System.ServiceModel.ClientBase<ClientWithProxyClass.ServiceReference.IDiskInfo>, ClientWithProxyClass.ServiceReference.IDiskInfo {
        
        public DiskInfoClient() {
        }
        
        public DiskInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiskInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiskInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiskInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long GetTotalSpace(string strDiskName) {
            return base.Channel.GetTotalSpace(strDiskName);
        }
        
        public System.Threading.Tasks.Task<long> GetTotalSpaceAsync(string strDiskName) {
            return base.Channel.GetTotalSpaceAsync(strDiskName);
        }
        
        public long GetFreeSpace(string strDiskName) {
            return base.Channel.GetFreeSpace(strDiskName);
        }
        
        public System.Threading.Tasks.Task<long> GetFreeSpaceAsync(string strDiskName) {
            return base.Channel.GetFreeSpaceAsync(strDiskName);
        }
    }
}
